### ISSUE TITLE
Missing data and/or examples

### ISSUE THREAD

**Issue by WoVollmer** [fabian-s/stabpath#5]
Hi,

Package "stabpath" does not provide any examples nor any data. Therefore it is  very difficult to know how to call get_stability_paths() with the right model and data inputs.

However, in my distress I tried the example from lab_stabsel.pdf (out of stabilityselection.zip) from FoRt "25.10. - 01.11. Programmierstil & Programmentwurf".

[lab_stabsel.pdf](https://github.com/fabian-s/stabpath/files/1682738/lab_stabsel.pdf)

However, this throws an error:
(strata <- rep(c("s1", "s2", "s3"), each=4))
tapply(X = 1:12, INDEX = strata, FUN = sample, replace = TRUE)

data(prostate)
data <- prostate
max_formula <- lpsa ~ (. - train)
model <- regsubsets(max_formula, data=data, nbest = 1, nvmax = 8,
  really.big = TRUE)

set.seed(20141020)
stability_paths <- get_stability_paths(model, data, reps=10)

### Error message #####################################

Error in `leaps::regsubsets`(max_formula, data = list(lcavol = c(2.830267834,  : 
  could not find function "leaps::regsubsets"

**Comment by fabian-s** [comment]
See https://github.com/fabian-s/stabpath/commit/a5675773123372bd6c0ed89eb7cefb04ba9fe102 for the actual fix of the problem in `refit.regsubsets`

**Comment by WoVollmer** [comment]
Fix in function refit.regsubsets() solves the issue properly. 
Takeover example for get_stability_paths is very useful. 
However, instead of storing function return value in variable 'stability_paths <- get_ ......'
direct console print out 
'get_stability_paths(model, data, reps=10)'
should be prefered.

**Comment by fabian-s** [comment]
> direct console print out
'get_stability_paths(model, data, reps=10)'
should be prefered.

Well, maybe. If you want to change this make a PR with your proposed changes.
